[project]
name = "discord-issues"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py>=2.5.2",
    "sqlalchemy>=2.0.41",
]
[dependency-groups]
dev = [
    "black>=25.1.0",
]
