"""Changed guild_issue_id to project_issue_id

Revision ID: 68f46830f9ce
Revises: 3142d47234a8
Create Date: 2025-06-25 02:10:15.032441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f46830f9ce'
down_revision: Union[str, Sequence[str], None] = '3142d47234a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_issue_id', sa.Integer(), nullable=False))
        batch_op.drop_column('guild_issue_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guild_issue_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('project_issue_id')

    # ### end Alembic commands ###
